---
  - hosts: all
    become: true
    become_user: pankaj
    gather_facts: true
    tasks:
      - name: Ansible copy file to remote server
        copy:
          src: ~/Downloads/Anaconda3-2019.03-Linux-x86_64.sh
          dest: ~/Downloads/Anaconda3-2019.03-Linux-x86_64.sh
      - name: Run the installer Anaconda
        expect:
          command: bash ~/Downloads/Anaconda3-2019.03-Linux-x86_64.sh
          responses:
          'please, press ENTER to continue' : ""
     